### ISSUE TITLE
Back End Development

### ISSUE THREAD

**Issue by khyatibhuva** [nisargptl/vehicle-recognition#2]
Integration of Front end with Database is pending.

**Comment by ajaykvala** [comment]
Basic integration is done and now we are able to complete our Search and Compare feature thoroughly. We are diving into Queryset in Django part for our Filter feature and will try and complete it soon. Also since the front-end for recommendation part is done for the Home page (Search feature), we will incorporate the back-end for the same and would update here.

**Comment by khyatibhuva** [comment]
Noted. The progress seems fast.

**Comment by khyatibhuva** [comment]
Once, you are done with any page. Upload it here.

**Comment by ajaykvala** [comment]
Sure, will do so.

**Comment by nisargptl** [comment]
Filter page is done. So, now all the functionalities have been added and all the pages have been routed. Now, only the image database integration part is remaining.

**Comment by shabbirmur** [comment]
Final integration is done. Nisarg please check the uploaded files.

**Comment by nisargptl** [comment]
Updates are completed. Everything is done and working perfect.
